platform:ios,'9.0'
target 'MONO' do
use_frameworks!

pod 'SnapKit'
pod 'MJRefresh'
pod 'RxSwift'
pod 'RxCocoa'
pod 'Alamofire'
pod 'HandyJSON'
pod 'RealmSwift'
pod 'pop'
pod 'MBProgressHUD'
pod 'Hero'
pod 'Kingfisher'

end
